import 'models/item_model.dart';

List<Item> items = [
  Item(id: 1, name: "Item 1"),
  Item(id: 2, name: "Item 2"),
  Item(id: 3, name: "Item 3"),
  Item(id: 4, name: "Item 4"),
  Item(id: 5, name: "Item 5"),
  Item(id: 6, name: "Item 6"),
  Item(id: 7, name: "Item 7"),
  Item(id: 8, name: "Item 8"),
  Item(id: 9, name: "Item 9"),
  Item(id: 10, name: "Item 10"),
  Item(id: 12, name: "Item 12"),
  Item(id: 13, name: "Item 13"),
  Item(id: 14, name: "Item 14"),
  Item(id: 15, name: "Item 15"),
  Item(id: 16, name: "Item 16"),
  Item(id: 17, name: "Item 17"),
  Item(id: 18, name: "Item 18"),
  Item(id: 19, name: "Item 19"),
  Item(id: 20, name: "Item 20"),
  Item(id: 21, name: "Item 21"),
  Item(id: 22, name: "Item 22"),
  Item(id: 23, name: "Item 23"),
  Item(id: 24, name: "Item 24"),
  Item(id: 25, name: "Item 25"),
  Item(id: 26, name: "Item 26"),
  Item(id: 27, name: "Item 27"),
  Item(id: 28, name: "Item 28"),
  Item(id: 29, name: "Item 29"),
  Item(id: 30, name: "Item 30"),
];
